# Crawler settings

# Logging config
logging:
  # level, must be one of:
  # NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: DEBUG

  # asyncioLevel, level of logging for asyncio.
  # With the same constraints as "level"
  asyncioLevel: DEBUG

  # output, must be one of:
  # console, daily_rotating_file
  output: console
